In [1]:
# Import Required Libraries
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

## Part 1 : Importing Data and Feature transformation

In [3]:
# Import Data
df = pd.read_csv("house_price_full.csv")
df.head()

bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [4]:
X = df.copy()
# Remove target
y= X.pop('price')

In [5]:
# Perform scaler transform on data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Perform log transformation of target variable
y = np.log(y)

In [6]:
df_scaled = pd.DataFrame(X)
df_scaled

0         1
0   -0.433198 -0.753258
1    1.675735  1.457330
2   -0.433198 -0.188649
3   -0.433198 -0.121661
4    0.621269 -0.179079
..        ...       ...
494  0.621269  0.873582
495  1.675735  2.299459
496 -0.433198 -0.724549
497 -0.433198 -0.179079
498 -0.433198 -1.040347

[499 rows x 2 columns]

In [7]:
x1, x2 = df_scaled.iloc[0]

In [8]:
x = tf.constant([[x1,x2]],dtype=tf.float32)
x.numpy()

array([[-0.43319765, -0.7532575 ]], dtype=float32)

## Part:2 Forward Propagation with Single Neuron

In [10]:
# Manually specifying weight and biases
w1 = tf.Variable([0.2],dtype=tf.float32)
w2 = tf.Variable([0.15],dtype=tf.float32)
b = tf.Variable([0.1],dtype=tf.float32)

In [11]:
z = b +w1*x1+w2*x2
h = tf.math.sigmoid(z)
print("Output of first neuron:",h)

Output of first neuron: tf.Tensor([0.47511354], shape=(1,), dtype=float32)


## Part:3 Forward Propagation with Multiple Neurons

In [13]:
# Manually specifying weight and biases
# neuron 1
b1 =tf.Variable([0.1],dtype=tf.float32)
w11 =tf.Variable([0.2],dtype=tf.float32)
w12 =tf.Variable([0.15],dtype=tf.float32)

# neuron 2
b2 =tf.Variable([0.25],dtype=tf.float32)
w21 =tf.Variable([0.5],dtype=tf.float32)
w22 =tf.Variable([0.6],dtype=tf.float32)

In [14]:
# Forward Pass
#neuron 1
z1 = b1 +w11*x1+w12*x2
h1 = tf.math.sigmoid(z1)
print("Output of first neuron:",h1)

Output of first neuron: tf.Tensor([0.47511354], shape=(1,), dtype=float32)


In [15]:
# Forward Pass
#neuron 2
z2 = b2 +w21*x1+w22*x2
h2 = tf.math.sigmoid(z2)
print("Output of first neuron:",h2)

Output of first neuron: tf.Tensor([0.39686295], shape=(1,), dtype=float32)


In [16]:
# Layer 2 weight and bias
b1 =tf.Variable([0.4],dtype=tf.float32)
w11 =tf.Variable([0.3],dtype=tf.float32)
w12 =tf.Variable([0.2],dtype=tf.float32)

In [17]:
# Forward Pass
#nSecond layer
z1 = b1 +w11*h1+w12*h2
h1 = z1
print("Output of first neuron:",h1)

Output of first neuron: tf.Tensor([0.62190664], shape=(1,), dtype=float32)


In [18]:
y_true = y[0]
y_pred = h1.numpy()

In [19]:
# Loss
l = 0.5*(y_true-y_pred)**2
print("loss :",l)

loss : [72.38514]


## Part 4 Forward pass matrix multiplication

In [21]:
## Layer 1 weights
W1 = tf.Variable([[0.2,0.15],[0.5,0.6]],dtype=tf.float32)
## Layer 1 bias
B1 = tf.Variable([[0.1],[0.25]],dtype=tf.float32)

In [22]:
## Layer 2 weights
W2 = tf.Variable([[0.3,0.2]],dtype=tf.float32)
## Layer 2 bias
B2 = tf.Variable([[0.4]],dtype=tf.float32)

In [23]:
## data
X = tf.constant([[x1,x2]],dtype=tf.float32)

In [24]:
## forward pass layer 1
Z1 = tf.add(tf.matmul(W1,tf.transpose(X)),B1)
H1 = tf.sigmoid(Z1)
print(H1)

tf.Tensor(
[[0.47511354]
 [0.39686295]], shape=(2, 1), dtype=float32)


In [25]:
## forward pass layer2
Z2 = tf.add(tf.matmul(W2,H1),B2)
H2 = tf.sigmoid(Z2)
print(H2)

tf.Tensor([[0.65065205]], shape=(1, 1), dtype=float32)


In [26]:
loss= 0.5 *(y_true-H2.numpy())**2
loss

array([[72.03968]], dtype=float32)

## Part 5 : Random Weight Initialization

In [28]:
def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2,2)))
    b1 = tf.Variable(tf.random.uniform((1,2)))
    w2 = tf.Variable(tf.random.uniform((2,1)))
    b2 = tf.Variable(tf.random.uniform((1,1)))
    return w1,b1,w2,b2

In [29]:
x = tf.constant([[x1,x2]],dtype=tf.float32)
y = y[0]

In [30]:
w1,b1,w2,b2 =random_init_params()

In [31]:
print("Initialized weights of layer 1",w1.numpy())
print("Initialized bias of layer 1",b1.numpy())
print("Initialized weights of layer 2",w2.numpy())
print("Initialized bias of layer 2",b2.numpy())

Initialized weights of layer 1 [[0.5299659  0.05304074]
 [0.34253514 0.33188236]]
Initialized bias of layer 1 [[0.62743306 0.5140215 ]]
Initialized weights of layer 2 [[0.36525857]
 [0.18009448]]
Initialized bias of layer 2 [[0.45328546]]


In [32]:
def forward_prop(x,w1,b1,w2,b2):
    z1 = tf.add(tf.matmul(x,w1),b1)
    h1 = tf.sigmoid(z1)
    z2 =tf.add(tf.matmul(h1,w2),b2)
    h2 =z2
    return h2

In [33]:
y_pred =forward_prop(x,w1,b1,w2,b2)
loss =0.5*(y -y_pred)**2
loss

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[70.85793]], dtype=float32)>

## Part 6: Backpropagation

In [35]:
x = tf.Variable(0.0)
ls = eta =0.1

In [36]:
with tf.GradientTape() as tape:
    y = x**2+4*x
grad = tape.gradient(y,x)

In [37]:
grad.numpy()

4.0

In [38]:
x.assign_sub(eta*grad)


<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=-0.4000000059604645>

In [39]:
x.numpy()

-0.4

In [40]:
## full loop
x= tf.Variable(0.0)
lr =0.1
for i in range(10):
    with tf.GradientTape() as tape:
        y=x**2+4*x
    grad =tape.gradient(y,x)
    x.assign_sub(lr*grad)
    print(x.numpy())

-0.4
-0.72
-0.9760001
-1.1808001
-1.34464
-1.4757121
-1.5805696
-1.6644557
-1.7315645
-1.7852516


In [41]:
# Read data
df = pd.read_csv("house_price_full.csv")
X = df.copy()
Y = X.pop("price")
scaler = StandardScaler()
X = scaler.fit_transform(X)
Y=np.log(Y)
df_scaled = pd.DataFrame(X)
x1,x2 =df_scaled.iloc[0]
df_scaled.head()

0         1
0 -0.433198 -0.753258
1  1.675735  1.457330
2 -0.433198 -0.188649
3 -0.433198 -0.121661
4  0.621269 -0.179079

In [42]:
x = tf.constant([[x1,x2]],dtype=tf.float32)
y=Y[0]

In [43]:
def random_init_param():
    w1 = tf.Variable(tf.random.uniform((2,2)))
    b1 = tf.Variable(tf.random.uniform((2,1)))
    w2 = tf.Variable(tf.random.uniform((1,2)))
    b2 = tf.Variable(tf.random.uniform((1,1)))
    return w1,b1,w2,b2

def forward_prop(x,w1,b1,w2,b2):
    z1=tf.add(tf.matmul(w1,tf.transpose(x)),b1)
    h1 = tf.sigmoid(z1)
    z2 =tf.add(tf.matmul(w2,h1),b2)
    h2=z2
    return h2

In [44]:
w1,b1,w2,b2 =random_init_param()

In [45]:
with tf.GradientTape() as tape:
    y_pred=forward_prop(x,w1,b1,w2,b2)
    loss =0.5*(y-y_pred)**2

In [46]:
gw1,gb1,gw2,gb2=tape.gradient(loss,[w1,b1,w2,b2])

In [88]:
print(gw1)

tf.Tensor(
[[0.08976761 0.15609069]
 [0.3228991  0.561467  ]], shape=(2, 2), dtype=float32)


In [90]:
print(gb1)

tf.Tensor(
[[-0.2072209 ]
 [-0.74538517]], shape=(2, 1), dtype=float32)


In [92]:
print(gw2)

tf.Tensor([[-7.2064714 -5.853784 ]], shape=(1, 2), dtype=float32)


In [94]:
print(gb2)

tf.Tensor([[-12.310982]], shape=(1, 1), dtype=float32)


In [96]:
lr =0.1
w1.assign_sub(lr*gw1)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[0.3081258 , 0.44940588],
       [0.5431983 , 0.43124524]], dtype=float32)>