In [39]:
tf.__version__

'2.18.0'

# 1. Tensors of different ranks

In [23]:
""" A vector is a one dimensional vector"""

# Vector in TensorFlow
vector_tf = tf.constant([0,1,2,3,4])

# Vector in Numpy
vector_np = np.array([0,1,2,3,4])

print("Shapes: ",vector_tf.shape,vector_np.shape)

Shapes:  (5,) (5,)


In [31]:
"""A matrix is a two dimensional vector """

# Matrix in Tensorflow
matrix_tf = tf.constant([[1,2],[3,4],[5,6]])

# Matrix in Numpy
matrix_np = np.array([[1,2],[3,4],[5,6]])

print("Shapes:", matrix_tf.shape, matrix_np.shape)

Shapes: (3, 2) (3, 2)


In [35]:
""" 3-D Tensor """

# 3-D Tensor in Tensorflow
t3_tf = tf.constant([[[1,2],[2,3],[3,4]]] *5)

# 3-D Tensor in Numpy
t3_np = np.array([[[1,2],[2,3],[3,4]]]*5)

print("Shapes:",t3_tf.shape,t3_np.shape)

Shapes: (5, 3, 2) (5, 3, 2)


In [37]:
print(t3_tf)

tf.Tensor(
[[[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]], shape=(5, 3, 2), dtype=int32)


# 2. Declaring a Tensor

In [ ]:
# Tensor constant
tf_const = tf.constant([[1,2,3],[4,5,6]])
# Tensor variable
tf_variable = tf.Variable([[1,2,3],[4,5,6]])

In [ ]:
# tf.constant - values cannot be changed once assigned,It must be initialised with a value, deriavtes are not calculated
x= tf.constant([1,2])
#x= x.assign([3,4]) # raises exception

In [ ]:
# tf.Variable - values can be changed by an operation or tf.assign,
y = tf.Variable([1,2])
y=y.assign_add([1,1])
y
y=y.assign([7,8])
y

In [48]:
# Declaring tensors with specific datatypes
int32_tensor = tf.Variable([[1,2,3],[3,4,5],[4,5,6]],dtype=tf.int32)
float32_tensor = tf.Variable([[1,2,3],[3,4,5],[4,5,6]],dtype=tf.float32)
bool_tensor = tf.Variable([True, False, True],dtype=tf.bool)

print("Int tensor ",int32_tensor)
print("Float tensor ",float32_tensor)
print("Boolean tensor ",bool_tensor)

Int tensor  <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])>
Float tensor  <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [3., 4., 5.],
       [4., 5., 6.]], dtype=float32)>
Boolean tensor  <tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False,  True])>


In [52]:
int32_tensor.numpy()

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [56]:
### Question:Declare a tensor of shape (2, 2, 2, 2) with random numbers from a normal distribution whose mean and standard deviation are both 1.
arr = np.random.randn(2,2,2,2) # return random numbers from standard normal deviation std=1 mean =0
print(arr.shape)
print(arr)

(2, 2, 2, 2)
[[[[ 1.44342753  0.63932183]
   [-1.92072604  1.30162577]]

  [[ 1.20843999  1.33508126]
   [-1.96829004  0.26878499]]]


 [[[ 0.39870035  0.28302356]
   [-0.98641936  1.07375872]]

  [[-0.59998849  1.12242058]
   [ 1.35009788  1.15795856]]]]


In [58]:
arr = arr+1 # Adding 1 to standard normal deviation to make mean 1

In [62]:
arr_tf = tf.constant(arr)
print(arr_tf)

tf.Tensor(
[[[[ 2.44342753  1.63932183]
   [-0.92072604  2.30162577]]

  [[ 2.20843999  2.33508126]
   [-0.96829004  1.26878499]]]


 [[[ 1.39870035  1.28302356]
   [ 0.01358064  2.07375872]]

  [[ 0.40001151  2.12242058]
   [ 2.35009788  2.15795856]]]], shape=(2, 2, 2, 2), dtype=float64)


In [66]:
# Approah 2 Using random generating function from tensorflow
arr2_tf = tf.random.normal((2,2,2,2), mean =1 ,stddev=1, name ="my_tensor")
print(arr2_tf)


tf.Tensor(
[[[[ 0.986637    2.08403   ]
   [ 0.68057406  1.2816325 ]]

  [[ 0.89850014 -0.3311442 ]
   [ 1.8719803   0.68684256]]]


 [[[ 1.3933566   1.4756823 ]
   [ 2.3903937   1.2133412 ]]

  [[ 2.501292    0.47168297]
   [-0.16036129  0.08113462]]]], shape=(2, 2, 2, 2), dtype=float32)


# 3. Common Mathematical Operation on Tensors

In [74]:
x = tf.Variable([list(range(5))]*5)
y = tf.Variable([list(range(5,10))]*5)
print(x)
print(y)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])>
<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])>


In [76]:
"""Simple mathematical operations on tensors"""
z= x+y
print(z)

tf.Tensor(
[[ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]], shape=(5, 5), dtype=int32)


In [78]:
v =x*y
print(v)

tf.Tensor(
[[ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]], shape=(5, 5), dtype=int32)


In [80]:
w = y/x
print(w)

tf.Tensor(
[[       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]], shape=(5, 5), dtype=float64)


In [82]:
z=tf.add(x,y)
v=tf.multiply(x,y)
w=tf.divide(y,x)

In [94]:
# Initialise a 2-by-2 tensor with all integer values and then create another tensor by squaring all the elements in the first tensor.
a = tf.random.uniform((2,2),minval=1, maxval=10,dtype=tf.int32)
print("Orginal tensor",a.numpy())
s= tf.pow(a,2) # s=  tf.multiple(a,a)
print("Squared tensor",s.numpy()) 


Orginal tensor [[5 7]
 [1 1]]
Squared tensor [[25 49]
 [ 1  1]]


# 4. Linear Algebra on Tensors

In [103]:
x = tf.Variable([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
y= tf.Variable([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
z = tf.linalg.matmul(x,y)
print(z.numpy())

[[ 135  150  165]
 [ 310  350  390]
 [ 485  550  615]
 [ 660  750  840]
 [ 835  950 1065]]


In [107]:
x =tf.cast(x,tf.float32)
print(x.numpy())

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [111]:
z = tf.linalg.inv(x)
print(z.numpy())

[[ -139809.53  -559241.1   1048576.     139810.1   -489335.72]
 [-6116693.5   9087660.          0.   -2796203.2   -174762.8 ]
 [ 6361360.5  -8108989.5  -2097152.    3075823.5    768956.1 ]
 [ 6186597.5  -8808039.          0.    1677721.9    943718.56]
 [-6291455.    8388609.    1048576.   -2097152.2  -1048576.2 ]]


In [121]:
t = tf.linalg.matmul(z,x)
print(t.numpy())

[[-9.09375  -8.8125   -9.53125  -9.25     -9.96875 ]
 [-4.234375 -3.53125  -2.328125  0.875    -1.921875]
 [ 6.625     2.75      2.875     3.       -0.875   ]
 [ 5.8125    4.375    -1.0625   -0.5      -3.9375  ]
 [-1.25      0.5       2.25      2.        1.75    ]]


In [119]:
"""Solve the following system of linear equations using TensorFlow:

x + y + z + w = 13

2x + 3y − w = −1

−3x + 4y + z + 2w = 10

x + 2y − z + w = 1

Ans: x = 2, y = 0, z = 6 , w = 5"""

'Solve the following system of linear equations using TensorFlow:\n\nx + y + z + w = 13\n\n2x + 3y − w = −1\n\n−3x + 4y + z + 2w = 10\n\nx + 2y − z + w = 1\n\nAns: x = 2, y = 0, z = 6 , w = 5'

In [127]:
coeff = tf.Variable([[1,1,1,1],[2,3,0,-1],[-3,4,1,2],[1,2,-1,1]],dtype=tf.float32)
y= tf.Variable([[13],[-1],[10],[1]],dtype=tf.float32)
inv_coff = tf.linalg.inv(coeff)
solution =tf.linalg.matmul(inv_coff,y)
print(solution)

tf.Tensor(
[[ 2.0000000e+00]
 [-1.1920929e-07]
 [ 5.9999995e+00]
 [ 5.0000000e+00]], shape=(4, 1), dtype=float32)


Question 1
The weights and the bias term of a trained model logistic regression model are given below. 

w1 = 0.5, w2 = 1 , w3 = -1.2 

b = 0.01

The features of a certain data point are given below.

​x1 = 0.2, x2 = 1, x3 = 0.5

Using TensorFlow, find the probability of the data point belonging to the positive class.

In [142]:
x =tf.Variable([[0.2,1,0.5]])
w =tf.Variable([[0.5],[1],[-1.2]])
b=tf.Variable([[0.01]])
z= tf.add(tf.linalg.matmul(x,w),b)
print(z.numpy())
p = tf.sigmoid(z)
print(p[0][0])

[[0.51]]
tf.Tensor(0.62480646, shape=(), dtype=float32)
